'use client';

import { SignIn } from '@clerk/nextjs';
import { Brain } from 'lucide-react';
import Link from 'next/link';

export default function SignInPage() {
  return (
      <div className="min-h-screen bg-[#020205] text-[#E2E8F0] font-sans selection:bg-blue-500/30 overflow-x-hidden flex items-center justify-center">
            <div className="fixed inset-0 -z-10 overflow-hidden pointer-events-none">
                    <div className="absolute top-[-10%] left-[-10%] w-[40%] h-[40%] bg-blue-900/20 rounded-full blur-[120px] animate-pulse" />
                            <div className="absolute bottom-[-10%] right-[-10%] w-[50%] h-[50%] bg-purple-900/10 rounded-full blur-[150px] animate-pulse" style={{ animationDelay: '2s' }} />
                                    <div className="absolute inset-0 bg-[url('https://grainy-gradients.vercel.app/noise.svg')] opacity-20 brightness-100 contrast-150" />
                                          </div>

                                                <div className="w-full max-w-md px-8 relative z-10">
                                                        <div className="flex items-center gap-4 mb-16 group cursor-pointer justify-center">
                                                                  <div className="relative">
                                                                              <div className="absolute inset-0 bg-blue-600 rounded-full blur-md opacity-50 group-hover:opacity-100 transition-opacity" />
                                                                                          <div className="relative w-12 h-12 bg-gradient-to-br from-blue-600 to-indigo-700 rounded-full flex items-center justify-center shadow-2xl">
                                                                                                        <Brain className="w-7 h-7 text-white" />
                                                                                                                    </div>
                                                                                                                              </div>
                                                                                                                                        <div className="flex flex-col">
                                                                                                                                                    <span className="text-2xl font-black tracking-tighter leading-none text-white">AIRA MENTOR</span>
                                                                                                                                                                <span className="text-[10px] font-bold tracking-[0.3em] text-blue-400 uppercase">Neural Focus Engine</span>
                                                                                                                                                                          </div>
                                                                                                                                                                                  </div>
                                                                                                                                                                                  
                                                                                                                                                                                          <div className="mb-8 glass-morphism p-8 rounded-3xl">
                                                                                                                                                                                                    <h2 className="text-2xl font-black mb-2 text-white uppercase tracking-tighter">Welcome Back</h2>
                                                                                                                                                                                                              <p className="text-sm text-gray-400 mb-8">Continue your neural journey.</p>
                                                                                                                                                                                                              
                                                                                                                                                                                                                        <SignIn
                                                                                                                                                                                                                                    appearance={{
                                                                                                                                                                                                                                                  elements: {
                                                                                                                                                                                                                                                                  rootBox: 'w-full',
                                                                                                                                                                                                                                                                                  card: 'bg-transparent border-0 shadow-none',
                                                                                                                                                                                                                                                                                                  headerTitle: 'hidden',
                                                                                                                                                                                                                                                                                                                  headerSubtitle: 'hidden',
                                                                                                                                                                                                                                                                                                                                  socialButtonsBlockButton: 'bg-white/5 border border-white/10 text-white hover:bg-white/10 font-bold rounded-xl mb-4',
                                                                                                                                                                                                                                                                                                                                                  socialButtonsBlockButtonText: 'text-sm font-bold',
                                                                                                                                                                                                                                                                                                                                                                  dividerLine: 'bg-white/10',
                                                                                                                                                                                                                                                                                                                                                                                  dividerText: 'text-gray-500 text-sm',
                                                                                                                                                                                                                                                                                                                                                                                                  formFieldLabel: 'text-white/80 font-bold uppercase text-xs tracking-wider mb-2',
                                                                                                                                                                                                                                                                                                                                                                                                                  formFieldInput: 'bg-white/5 border border-white/10 text-white placeholder-gray-600 rounded-xl focus:border-blue-500/50 focus:outline-none py-3',
                                                                                                                                                                                                                                                                                                                                                                                                                                  formButtonPrimary: 'bg-blue-600 hover:bg-blue-700 text-white font-black uppercase tracking-widest rounded-xl py-3 w-full',
                                                                                                                                                                                                                                                                                                                                                                                                                                                  footerActionLink: 'text-blue-400 hover:text-blue-300 font-bold text-sm',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              variables: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              colorPrimary: '#3B82F6',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              colorText: '#E2E8F0',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              colorTextSecondary: '#9CA3AF',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              colorBackground: '#020205',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    signUpUrl="/sign-up"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                redirectUrl="/dashboard"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="relative my-8">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="absolute inset-0 flex items-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="w-full border-t border-white/10" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="relative flex justify-center text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span className="px-2 bg-[#020205] text-gray-500 text-xs font-bold">NEW HERE?</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Link href="/sign-up" className="block w-full py-4 rounded-xl bg-white text-black font-black text-center hover:scale-105 transition-all uppercase tracking-widest shadow-xl">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Create Account
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="mt-12 text-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Link href="/" className="text-sm text-gray-500 hover:text-gray-400 transition-colors font-bold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ← Back to Home
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
